CREATE SEQUENCE item_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE item
(
    id          BIGINT NOT NULL,
    create_date TIMESTAMP,
    name        VARCHAR(255),
    CONSTRAINT pk_item PRIMARY KEY (id)
);

CREATE TABLE team
(
    id   INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(1000000000)                  NOT NULL,
    CONSTRAINT pk_team PRIMARY KEY (id)
);

ALTER TABLE item
    ADD CONSTRAINT uc_item_name UNIQUE (name);
